### ISSUE TITLE
"sh: 1: hdfs: not found" encountered with "setup-yarn-2.sh" script

### ISSUE THREAD

**Issue by ohohoreilly** [eBay/myriad#1]
I'm seeing the following behavior when trying to run the "setup-yarn-2.sh" script.

```
Hadoop 2.5.0
Subversion http://svn.apache.org/repos/asf/hadoop/common -r 1616291
Compiled by jenkins on 2014-08-06T17:31Z
Compiled with protoc 2.5.0
From source with checksum 423dcd5a752eddd8e45ead6fd5ff9a24
This command was run using /usr/local/hadoop/share/hadoop/common/hadoop-common-2.5.0.jar
sh: 1: hdfs: not found
```

**Comment by mohitsoni** [comment]
@preillyme This is no longer the active fork, we forked the project under mesos community umbrella: https://github.com/mesos/myriad, and are continuing development there.

I'll update this project page to reflect that.

**Comment by ohohoreilly** [comment]
Okay I'll move my question over to the correct repo.
